# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'DatXanhManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'OneSignal'
  pod 'Toaster'
  pod 'Cosmos'

  # Pods for DatXanhManagement

end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'OneSignal'

  # Pods for OneSignalNotificationServiceExtension

end
